"use client";
import { useState } from "react";
const questions = [
 ["I’m a complete beginner. Is this for me?", "Yes. Start with the roadmap, choose one service and work through the daily tasks. You’ll need internet access, time to practise and a willingness to speak with potential customers. No coding is required for the core service path."],
 ["What exactly will I receive?", "15 PDF guides and 6 editable Excel workbooks, including the main playbook, 30 service ideas, a 30-day workbook, 150 prompts, outreach examples and trackers. Everything is digital. The book images are illustrative mockups; no physical books are shipped."],
 ["Do I need paid AI tools?", "You can start practising with free AI tools where available. Some services may need paid software or API usage later. Those third-party costs are separate from the kit."],
 ["Will I get a client in 30 days?", "That isn’t guaranteed. The 30 days give you a structure for building an offer, creating proof and starting conversations. Results depend on your skills, execution, market and the people you contact. The workbook also helps you diagnose what to improve if you haven’t found a client yet."],
 ["Can I use this alongside college or a job?", "Yes. Work at your own pace. Many tasks fit into a focused session, while creating a portfolio sample or delivering a project can take longer. The 30-day plan is a guide, not a deadline."],
 ["How do payment and access work?", "Pay once through Dodo Payments. Once your payment is confirmed, you’ll be taken to the Google Drive folder containing the kit. Your Dodo purchase email also provides access. There is no kit subscription."],
];
export default function Home() {
 const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function buy(){if(busy)return;setBusy(true);setError("");try{const res=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"}});const data=await res.json() as {url?:string;error?:string};if(!res.ok||!data.url)throw new Error(data.error||"Checkout couldn’t open. Please try again.");window.location.assign(data.url);}catch(err){setError(err instanceof Error?err.message:"Please try again.");setBusy(false);}}
 const cta=(label="Get the kit — ₹499",style="button")=><button className={style} onClick={buy} disabled={busy}>{busy?"Opening checkout…":label}<span aria-hidden="true">↗</span></button>;
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <header className="nav wrap"><a className="brand" href="#" aria-label="AI Income Starter Kit home"><span className="brand-symbol">ai<span>↗</span></span><span>AI INCOME<br/>STARTER KIT</span></a><nav aria-label="Main navigation"><a href="#inside">The kit</a><a href="#questions">Questions</a>{cta("Get access","button nav-cta")}</nav></header>
 <main id="main"><section className="hero wrap"><div className="eyebrow"><span className="little-line"/>YOUR FIRST STEP FROM AI TO CLIENT WORK</div><h1>Turn AI into your<br/><span className="green">first paying skill.</span></h1><p className="hero-copy">You’ve tried the tools. Now build something useful.<br className="desktop-break"/> Pick one service, create a clear offer, and start pursuing your first paid project.</p><div className="hero-actions">{cta()}<a className="text-link" href="#inside">Take a look inside <span aria-hidden="true">↓</span></a></div><p className="micro">One payment. PDF guides + editable Excel tools.</p><figure className="hero-art"><img src="/images/kit-books.webp" width="1536" height="1024" alt="Illustrative mockup of the AI Income Playbook, 30 AI Services, Get Your First Client and 30-Day Challenge books" fetchPriority="high"/><figcaption><span>THE AI INCOME STARTER KIT</span><span>A practical system. A clear next step.</span></figcaption></figure></section>
 <section className="perspective wrap" aria-labelledby="perspective-title"><p className="eyebrow">LESS TOOL HOPPING. MORE DOING.</p><h2 id="perspective-title">“I know AI.<br/>But what do I <em>sell?</em>”</h2><div className="perspective-copy"><p>That’s the gap this kit helps you close.</p><p>A business doesn’t need another prompt. It needs clearer product descriptions, useful research, consistent content, or a better way to get work done.</p><p className="strong">Learn to turn one of those problems into one useful service.</p></div><div className="offer-example"><div><span className="eyebrow">FROM A TOOL</span><p>“I use AI<br/>for content.”</p></div><span className="example-arrow" aria-hidden="true">→</span><div><span className="eyebrow">TO A USEFUL OFFER</span><p>“I turn your webinar into <strong>8 LinkedIn posts</strong>, checked and ready for your review.”</p><small>Illustrative offer · You check the facts, voice and quality.</small></div></div></section>
 <section className="inside" id="inside"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">A LOOK INSIDE</p><h2>Everything connects.<br/><span className="muted">So you can keep moving.</span></h2></div><a className="text-link" href="/preview.pdf" target="_blank" rel="noopener">Read a real sample <span aria-hidden="true">↗</span></a></div><div className="chapters"><article className="chapter"><div className="chapter-top"><span>01 / FIND YOUR DIRECTION</span><span aria-hidden="true">↗</span></div><h3>One skill.<br/>One clear offer.</h3><p>Compare 30 practical services. Choose a customer. Work out your price and build proof before you approach anyone.</p><div className="chapter-foot">The playbook · Service catalog · Pricing tools</div></article><article className="chapter dark"><div className="chapter-top"><span>02 / START THE CONVERSATION</span><span aria-hidden="true">↗</span></div><h3>Find people<br/>you can help.</h3><p>Research relevant businesses, personalise your message and handle your first sales conversation with a clear next step.</p><div className="chapter-foot">Acquisition guide · Outreach vault · Lead tracker</div></article><article className="chapter mint"><div className="chapter-top"><span>03 / PUT IT INTO PRACTICE</span><span aria-hidden="true">↗</span></div><h3>A little progress.<br/>Every day.</h3><p>Follow a focused 30-day plan, use prompts with purpose and learn how to deliver a project professionally.</p><div className="chapter-foot">Daily workbook · Prompt vault · Delivery system</div></article></div><p className="format-note">15 PDFs + 6 Excel workbooks. Downloadable, self-paced, and yours to work through.</p></div></section>
 <section className="daily wrap"><div className="daily-text"><p className="eyebrow">BUILT FOR YOUR FIRST REAL ATTEMPT</p><h2>You don’t need<br/>to do everything.<br/><span className="green">Just the next thing.</span></h2><p>For the student with a free evening. The fresher building a skill. The working professional ready to try a small service on the side.</p><p>Start where you are. Build a sample you’re proud of. Reach out with something useful to offer.</p><a className="text-link" href="#get-kit">Make your first move <span aria-hidden="true">↗</span></a></div><div className="day-card"><span className="eyebrow">YOUR 30-DAY ROADMAP</span><div className="day-row"><span>01—07</span><div><h3>Choose & shape</h3><p>One service, one customer, one offer.</p></div></div><div className="day-row"><span>08—15</span><div><h3>Build & research</h3><p>Honest proof and relevant prospects.</p></div></div><div className="day-row"><span>16—24</span><div><h3>Reach out & follow up</h3><p>Personal messages. Real conversations.</p></div></div><div className="day-row"><span>25—30</span><div><h3>Propose & improve</h3><p>Take the next step from what you learn.</p></div></div><p className="roadmap-note">A plan for taking action. No promise of income or a client by day 30.</p></div></section>
 <figure className="lifestyle"><img src="/images/workspace.webp" width="2048" height="768" loading="lazy" alt="Illustrative AI Income Starter Kit books on a sunlit workspace"/><figcaption>One customer. One useful service. One clear next step.</figcaption></figure>
 <section className="offer wrap" id="get-kit"><div className="offer-intro"><p className="eyebrow">START SMALL. BUILD SOMETHING USEFUL.</p><h2>Your next step<br/>is in the kit.</h2><p>Give your AI curiosity a direction. A practical system to help you choose, build, pitch and deliver.</p><span className="handwritten">Less scrolling. More starting.</span></div><div className="price-card"><div className="price-top"><span>THE COMPLETE DIGITAL KIT</span><span>ONE-TIME</span></div><div className="price">₹499<span>INR</span></div><p>15 PDF guides. 6 Excel workbooks.<br/>One practical 30-day system.</p>{cta("Get the AI Income Starter Kit","button price-button")}<div className="payment-note"><svg width="15" height="17" viewBox="0 0 18 20" fill="none" aria-hidden="true"><rect x="2" y="8" width="14" height="10" rx="2" stroke="currentColor" strokeWidth="1.5"/><path d="M5 8V5a4 4 0 0 1 8 0v3" stroke="currentColor" strokeWidth="1.5"/></svg>Secure checkout by Dodo Payments</div><p className="price-fine">Digital download · No subscription<br/>Any applicable tax and final total are shown at checkout.</p></div></section>
 <section className="faq wrap" id="questions"><div><p className="eyebrow">BEFORE YOU START</p><h2>A few good<br/>questions.</h2></div><div className="faq-items">{questions.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section></main>
 <footer className="footer wrap"><a className="brand" href="#"><span className="brand-symbol">ai<span>↗</span></span><span>AI INCOME<br/>STARTER KIT</span></a><p>Build a useful skill. Take a real next step.</p><div><a href="/purchase-information">Purchase & privacy</a><span>© {new Date().getFullYear()} AI Income Starter Kit</span></div><p className="disclosure">An independent educational product. Not affiliated with AI tool providers. Results vary; income and client acquisition are not guaranteed. Book images are illustrative digital-product mockups.</p></footer>
 <div className="mobile-bar"><div><strong>₹499</strong><span>One-time · Digital kit</span></div>{cta("Get the kit","button")}</div>{error&&<div role="alert" className="checkout-error"><span>{error}</span><button onClick={()=>setError("")} aria-label="Dismiss checkout message">×</button></div>}
 </>;
}
