import { env } from "cloudflare:workers";
type Config = { DODO_PAYMENTS_API_KEY?: string; DODO_PRODUCT_ID?: string; DODO_ENVIRONMENT?: string; SITE_URL?: string; CHECKOUT_SESSION_SECRET?: string; KIT_DELIVERY_URL?: string; DODO_PAYMENTS_WEBHOOK_KEY?: string };
export function config(){const e=env as unknown as Config; const get=(k:keyof Config)=>e[k]||process.env[k];const key=get('DODO_PAYMENTS_API_KEY');const product=get('DODO_PRODUCT_ID');const site=get('SITE_URL');const secret=get('CHECKOUT_SESSION_SECRET');const delivery=get('KIT_DELIVERY_URL');const webhookKey=get('DODO_PAYMENTS_WEBHOOK_KEY');const mode=get('DODO_ENVIRONMENT');if(!key||!product||!site||!secret||!delivery)throw new Error("Payment configuration unavailable");if(new URL(delivery).origin!=='https://drive.google.com')throw new Error('Invalid delivery destination');return {key,product,site,secret,delivery,webhookKey,base:mode==='test_mode'?'https://test.dodopayments.com':'https://live.dodopayments.com'};}
export type Product={price:{price:number;currency:string};is_recurring:boolean;digital_product_delivery?:{external_url?:string}};
export type Checkout={checkout_url:string;session_id:string};
export type PaymentStatus={payment_status?:string};
export async function dodo<T>(path:string,method='GET',body?:unknown):Promise<T>{const c=config();const r=await fetch(c.base+path,{method,headers:{Authorization:`Bearer ${c.key}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`Payment provider returned ${r.status}`);return r.json() as Promise<T>;}
export async function sign(value:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(config().secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return Array.from(new Uint8Array(sig)).map(b=>b.toString(16).padStart(2,'0')).join('');}
export async function session(request:Request){const raw=request.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('kit_checkout='))?.slice(13);if(!raw)return null;const [id,issued,signature]=raw.split('.');if(!/^cks_[a-zA-Z0-9]+$/.test(id)||!issued||!signature||Date.now()-Number(issued)>86400000||Number(issued)>Date.now())return null;const expected=await sign(id+'.'+issued);if(expected.length!==signature.length)return null;let diff=0;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^signature.charCodeAt(i);return diff===0?{id,issued:Number(issued)}:null;}
export function json(value:unknown,status=200,extra:Record<string,string>={}){return Response.json(value,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra}});}
